services:
  svc-order:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
  postgres:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
